#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 Takashi Iwasaki
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for lins in sys.stdin:
    try:
        ans += int(line)
    except:
        ant += float(line)

print(ans)

